import datetime as datetime

x=datetime.datetime.now()
print(x)
print(x.strftime('%A'))
print(x.strftime('%a'))
print(x.strftime('%m'))
print(x.strftime('%b'))
print(x.strftime('%B'))
print(x.strftime('%x'))
print(x.strftime('%X'))
print(x.strftime('%p'))
print(x.strftime('%f'))
print(x.strftime('%y'))
print(x.strftime('%Y'))

y=datetime.datetime(1947,10,2)
print("\n",y)
print(y.strftime('%A'))
print(y.strftime('%a'))
print(y.strftime('%m'))
print(y.strftime('%b'))
print(y.strftime('%B'))
print(y.strftime('%y'))
print(y.strftime('%Y'))
print(y.strftime('%p'))
print(y.strftime('%f'))
print(y.strftime('%S'))